# disable autofixing PRs, commenting "pre-commit.ci autofix" on a pull request triggers a autofix
ci:
    autofix_prs: false
# generally speaking we ignore all vendored code as well as tests data
exclude: |
  (?x)^(
    conda/_vendor |
    tests/data/(
      conda_format_repo |
      env_metadata/.+ |
      legacy_repodata |
      repodata |
      tar_traversal |
      corrupt
    ) |
    tools/vendoring/patches
  )/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # standard end of line/end of file cleanup
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # ensure syntaxes are valid
      - id: check-toml
      - id: check-yaml
        exclude: ^(conda\.)?recipe/meta.yaml
      # catch git merge/rebase problems
      - id: check-merge-conflict
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
        exclude: ^conda/exports.py
  - repo: https://github.com/akaihola/darker
    rev: 1.7.0
    hooks:
      - id: darker
        additional_dependencies: [black==22.10.0]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: insert-license
        files: \.py$
        args: [--license-filepath, .github/disclaimer.txt, --no-extra-eol]
        exclude: ^conda/auxlib/
