version: "3.9"

x-base: &base
  build:
    context: .
    # cache_from:
    #   - debian:buster-slim
    args:
      python_version: "${CONDA_DOCKER_PYTHON:-3.9}"
      default_channel: "${CONDA_DOCKER_DEFAULT_CHANNEL:-conda-forge}"
  volumes:
    - .:/opt/conda-src
  image: conda-linux-python-${CONDA_DOCKER_PYTHON:-3.9}-${CONDA_DOCKER_DEFAULT_CHANNEL:-defaults}
  container_name: conda-linux-python-${CONDA_DOCKER_PYTHON:-3.9}-${CONDA_DOCKER_DEFAULT_CHANNEL:-defaults}

services:
  interactive:
    <<: *base
    command: ["bash", "--rcfile", "/opt/conda-src/dev/linux/bashrc.sh"]

  integration-tests:
    <<: *base
    command: ["bash", "/opt/conda-src/dev/linux/integration.sh"]

  unit-tests:
    <<: *base
    command: ["bash", "/opt/conda-src/dev/linux/unit.sh"]
